Libname mona '/home/jkang.biostat/Lecture5';
TITLE 'week5q1';
DATA MASTER;
SET mona.vitam;
SET mona.demog;
INFILE '/home/jkang.biostat/Lecture3/fat.txt';
INPUT ID ENERGY TOTFAT TOTPFA TOTMFA TOTSFA;
RUN;

Title ' Jennifer Kang, Lab 5 Problem 2';
Data Centralized;
set master;
run;

Proc MEANS DATA=Centralized NOPRINT;
VAR TOTFAT TOTPFA TOTMFA TOTSFA;
OUTPUT OUT=SUMMARY MEAN=TOTFATM TOTPFAM TOTMFAM TOTSFAM;
run;


DATA CENTR;
IF _N_=1 THEN SET SUMMARY;
SET centralized;
TOTFATC=TOTFAT-TOTFATM;
TOTSFAC=TOTSFA-TOTSFAM;
TOTPFAC=TOTPFA-TOTPFAM;
TOTMFAC=TOTMFA-TOTMFAM;
KEEP TOTFAT TOTSFA TOTPFA TOTMFA TOTFATM TOTSFAM TOTPFAM TOTMFAM TOTFATC TOTSFAC TOTPFAC TOTMFAC;
run;
PROC PRINT;
RUN;
PROC CONTENTS DATA=CENTR;
RUN;


/*PROBLEM 3: Sex=1 is male and Sex=2 is female*/


PROC MEANS DATA=mona.DEMENT;
VAR AGEMENOP;
OUTPUT OUT=DEMEN Q1=AGE25 Q3=AGE75;
RUN;
DATA DEMENT2;
SET mona.DEMENT;
IF _N_=1 THEN SET DEMEN;
IF SEX=1 THEN AGEM=.;
IF SEX=2 AND AGEMENOP=. THEN AGEM=.;
IF 0<AGEMENOP<AGE25 THEN AGEM=1;
IF AGE25<AGEMENOP =<AGE75 THEN AGEM=2;
IF AGEMENOP> AGE75 THEN AGEM=3;

IF MMSE>=0 AND MMSE <=23 THEN MMSEC=1;
IF MMSE>23 THEN MMSEC=2;

PROC FREQ DATA=DEMENT2;
TABLE AGEM*MMSEC;
RUN;

